name: kibas_mobile
description: "A new Flutter project."

publish_to: 'none'

version: 4.0.0+4

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.4
  connectivity_plus: ^6.1.1
  dartz: ^0.10.1
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.14.1
  get_it: ^8.0.3
  go_router: ^14.3.0
  build_runner: ^2.3.3
  iconsax: ^0.0.8
  image_picker: ^1.0.2
  intl: ^0.20.1
  image: ^4.5.3
  get_storage: ^2.1.1
  path: ^1.9.0
  path_provider: ^2.1.5
  geolocator: ^13.0.3
  permission_handler: ^11.4.0
  http: ^1.3.0
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.6
  flutter_local_notifications: ^18.0.1
  open_file: ^3.5.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/logo_kibas.png"

flutter:

  uses-material-design: true

  assets:
    - assets/

fonts:
  - family: PlusJakartaSansBold
    fonts:
      - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Bold.ttf
        style: normal
      - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-BoldItalic.ttf
        style: italic
  - family: PlusJakartaSansSemiBold
    fonts:
      - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-SemiBold.ttf
        style: normal
      - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-SemiBoldItalic.ttf
        style: italic
  - family: PlusJakartaSansMedium
    fonts:
      - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Medium.ttf
        style: normal
      - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-MediumItalic.ttf
        style: italic
  - family: PlusJakartaSansRegular
    fonts:
      - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Regular.ttf
        style: normal
      - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Italic.ttf
        style: italic

  - family: PlusJakartaSansExtraLight
    fonts:
      - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-ExtraLight.ttf
        style: normal
      - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-ExtraLightItalic.ttf
        style: italic
  - family: PlusJakartaSansLight
    fonts:
      - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Light.ttf
        style: normal
      - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-LightItalic.ttf
        style: italic

